module.exports={
    VENDOR_COLLECTION:'vendor',
    USER_COLLECTION:'user',
    ADMIN_COLLECTION:'admin1',
    PRODUCT_COLLECTION:'product',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'order',
    CATEGORY_COLLECTION:'category',
    VENDOR_PROFILE:'vendorprofile',
    ADMIN_PROFILE:'adminprofile'
}